
package com.ushine.ssh.webcline;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-08T11:02:53.898+08:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.ssh.ushine.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.ushine.ssh.webcline.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.ushine.ssh.webcline.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.ushine.ssh.webcline.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.ushine.ssh.webcline.Exception getFaultInfo() {
        return this.exception;
    }
}
