package com.ushine.ssh.webcline;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-28T16:05:21.434+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://webservice.ssh.ushine.com/", name = "IWebServiceUpload")
@XmlSeeAlso({ObjectFactory.class})
public interface IWebServiceUpload {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sumitVocationalWorkSystemVersion", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitVocationalWorkSystemVersion")
    @WebMethod
    @ResponseWrapper(localName = "sumitVocationalWorkSystemVersionResponse", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitVocationalWorkSystemVersionResponse")
    public boolean sumitVocationalWorkSystemVersion(
        @WebParam(name = "han", targetNamespace = "")
        com.ushine.ssh.webcline.VocationalWorkSystemVersionHan han
    ) throws Exception_Exception;
}
