package com.ushine.ssh.webcline;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-08T11:02:53.945+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://webservice.ssh.ushine.com/", name = "IWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWebService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "saveSubordinateNodeInfo", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SaveSubordinateNodeInfo")
    @WebMethod
    @ResponseWrapper(localName = "saveSubordinateNodeInfoResponse", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SaveSubordinateNodeInfoResponse")
    public boolean saveSubordinateNodeInfo(
        @WebParam(name = "str", targetNamespace = "")
        com.ushine.ssh.webcline.SubordinateNodeInfo str
    ) throws Exception_Exception;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sumitBlackBoxData", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitBlackBoxData")
    @WebMethod
    @ResponseWrapper(localName = "sumitBlackBoxDataResponse", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitBlackBoxDataResponse")
    public boolean sumitBlackBoxData(
        @WebParam(name = "str", targetNamespace = "")
        java.util.List<com.ushine.ssh.webcline.BlackBoxStatusInfo> str
    ) throws Exception_Exception;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sumitVocationalWork", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitVocationalWork")
    @WebMethod
    @ResponseWrapper(localName = "sumitVocationalWorkResponse", targetNamespace = "http://webservice.ssh.ushine.com/", className = "com.ushine.ssh.webcline.SumitVocationalWorkResponse")
    public boolean sumitVocationalWork(
        @WebParam(name = "str", targetNamespace = "")
        com.ushine.ssh.webcline.VocationalWork str
    ) throws Exception_Exception;
}
