package com.ushine.ssh.webcline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-28T16:05:21.452+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "IWebServiceUploadService", 
                  wsdlLocation = "http://localhost:8080/ZFJD/services/webserviceUpload?wsdl",
                  targetNamespace = "http://webservice.ssh.ushine.com/") 
public class IWebServiceUploadService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ssh.ushine.com/", "IWebServiceUploadService");
    public final static QName IWebServiceUploadPort = new QName("http://webservice.ssh.ushine.com/", "IWebServiceUploadPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ZFJD/services/webserviceUpload?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IWebServiceUploadService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ZFJD/services/webserviceUpload?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IWebServiceUploadService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IWebServiceUploadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWebServiceUploadService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IWebServiceUploadService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IWebServiceUploadService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IWebServiceUploadService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IWebServiceUpload
     */
    @WebEndpoint(name = "IWebServiceUploadPort")
    public IWebServiceUpload getIWebServiceUploadPort() {
        return super.getPort(IWebServiceUploadPort, IWebServiceUpload.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebServiceUpload
     */
    @WebEndpoint(name = "IWebServiceUploadPort")
    public IWebServiceUpload getIWebServiceUploadPort(WebServiceFeature... features) {
        return super.getPort(IWebServiceUploadPort, IWebServiceUpload.class, features);
    }

}
