package com.ushine.ssh.webcline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-08T11:02:53.964+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "WebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/ZFJD/services/webservice?wsdl",
                  targetNamespace = "http://webservice.ssh.ushine.com/") 
public class WebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.ssh.ushine.com/", "WebServiceImplService");
    public final static QName WebServiceImplPort = new QName("http://webservice.ssh.ushine.com/", "WebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ZFJD/services/webservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ZFJD/services/webservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IWebService
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public IWebService getWebServiceImplPort() {
        return super.getPort(WebServiceImplPort, IWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebService
     */
    @WebEndpoint(name = "WebServiceImplPort")
    public IWebService getWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WebServiceImplPort, IWebService.class, features);
    }

}
